name: Run myos

on:
  push:

jobs:
  run-myos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Dockerfile
      run: docker build -t myos .

    - name: List Images
      run: docker images

    - name: Run Docker
      run: docker run -v .:/myos --name myos myos:latest
